// <auto-generated />
namespace avenabot.Migrations.EliminatorieMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ConsolazioneTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConsolazioneTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202101171425258_ConsolazioneTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
