// <auto-generated />
namespace avenabot.Migrations.EliminatorieMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FIDField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FIDField));
        
        string IMigrationMetadata.Id
        {
            get { return "202101181012301_FIDField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
